import test from "node:test";
import assert from "node:assert/strict";
import { generateRobloxLua, normalizeAssetIds } from "../src/lua-generator.js";

test("Lua generator normalizes unique Roblox Asset IDs", () => {
  assert.deepEqual(normalizeAssetIds("rbxassetid://12345, 67890 12345"), ["12345", "67890"]);
  assert.throws(() => normalizeAssetIds("no ids"), /valid Roblox Asset ID/);
});

test("Lua generator creates safe playlist templates", () => {
  for (const mode of ["single", "playlist", "random", "crossfade"]) {
    const lua = generateRobloxLua("12345,67890", mode);
    assert.match(lua, /Generated by Eclipse Audio/);
    assert.match(lua, /rbxassetid:\/\/12345/);
    assert.doesNotMatch(lua, /loadstring|HttpGet/);
  }
  assert.throws(() => generateRobloxLua("12345", "unsafe"), /Invalid Lua template/);
});
